export default [
  ["config-hook-time-freeze-number", "获取当前时间戳用于固定时间"],
  [
    "config-hook-time-performance",
    "config-hook-performance-now（这个时间函数返回的值固定成一个数字）",
  ],
  ["config-hook-log-at", "是否在调试输出时，输出函数触发的地址"],
  ["config-hook-cookie", "是否对 cookie 进行挂钩调试输出"],
  ["config-hook-cookie-add-debugger", "hook-cookie-add-debugger"],
  [
    "config-hook-cookie-match",
    "对匹配字符串的cookie才下断（不设置则为全部都下断）",
  ],
  ["hook-cookie-get", "hook-cookie-get"],
  ["hook-cookie-set", "hook-cookie-set"],
  ["config-hook-encrypt-normal", "是否启用下面几个加解密函数挂钩输出功能"],
  ["hook-JSON.parse", " config-hook-JSON.parse"],
  ["hook-JSON.stringify", " config-hook-JSON.stringify"],
  ["hook-decodeURI", " config-hook-decodeURI"],
  ["hook-decodeURIComponent", " config-hook-decodeURIComponent"],
  ["hook-encodeURI", " config-hook-encodeURI"],
  ["hook-encodeURIComponent", " config-hook-encodeURIComponent"],
  ["hook-escape", " config-hook-escape"],
  ["hook-unescape", " config-hook-unescape"],
  ["hook-atob", " config-hook-atob"],
  ["hook-btoa", " config-hook-btoa"],
  ["config-hook-domobj", "是否启用挂钩 DOM 对象的原型的功能调试输出"],
  ["config-hook-domobj-get", "hook-domobj-显示get输出"],
  ["config-hook-domobj-set", "hook-domobj-显示set输出"],
  ["config-hook-domobj-func", "hook-domobj-显示func输出"],
];
